### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by infusion** [porsager/postgres#10]
Hi Rasmus,

replacing `pg` with `postgres` on our dev branch worked like a charm. Testing the library for a bit longer and stress-testing it is now necessary. One thing I noted was that JSON-values must be stringified manually, which `pg` did behind the scenes. I don't know if this is possible here as well, such as

```js
let ob = {foo: 1, bar: 2}

sql`SELECT ${ob}`
```

which only works when stringify is used manually atm like this:

```js
let ob = {foo: 1, bar: 2}

sql`SELECT ${JSON.stringify(ob)}`
```

Thanks for sharing this amazing library!

Robert

**Comment by porsager** [comment]
Hi Robert.

That's really exciting. Would love to hear how everything works out eventually.

You should use `sql.json()` instead of `JSON.stringify()` since that will pass the correct type to postgres too. Eg.

```
let ob = { foo: 1, bar: 2 }
sql`select ${ sql.json() }`
```

The reason JSON values aren't automatically inferred is because it would lead to ambiguity about how to serialize values. `1, null, false` are for instance all valid JSON, but I think it's better to let postgres know `1` is an `int` and `null` is `NULL` and false is a `boolean`.

If you check out the comparrison in my benchmark, notice how much extra code/plumbing is needed for `pg` to do the right thing because everything is just stringified.
pg: https://github.com/porsager/postgres-benchmarks/blob/master/pg/index.js#L9-L25
postgres: https://github.com/porsager/postgres-benchmarks/blob/master/postgres/index.js#L9-L17

For instance you're also able to do the following which wouldn't be possible if we just did `JSON.stringify` on values.

```js
sql`select * from items where color in (${ ['blue', 'red', 'green'] })`
```

Looking at your example, you might be interested in knowing that you can do
```js
sql`select ${ sql({ foo: 1, bar: 2 }) }
```
and it will return `[{ foo: 1, bar: 2 }]`

I hope that clears it up.. Maybe this description would be good in the documentation too?

And thank you for the kind words too :)

**Comment by porsager** [comment]
I hope my explanation was fine, but feel free to open again or ask if you have any questions.
