### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by Emonora** [porsager/postgres#1001]
I use pnpm, and recieve this error among many other module not found errors, when this module is installed. I'm using the base t3-stack integration with drizzle. I've tried re-installing node to no avail, and was wondering if anyone could help.

**Comment by Mishankhatri** [comment]
Hi there @Emonora!
Also got similar issue on the my project (not t3 stack but drizzle + trpc  + postgres + Next js ) , the issue was similar and found out that it was issue was I was importing the zod schema defined on my one of router in client side form for parsing. I am not fully sure why this fixed the issue but it might be similar that you have imported some of the files from routers / schema /db to client side (Frontend) files.

**Comment by porsager** [comment]
Not postgres related
