### ISSUE TITLE
@2.0.0-beta.0, bigserial primary key returned as string?

### ISSUE THREAD

**Issue by joshxyzhimself** [porsager/postgres#105]
Hi there, II've decided to try out v2 beta because of https://github.com/porsager/postgres/issues/49; but previously on v1 the bigserial primary keys are returned as integers, is there just something wrong with my code?

- TABLE:

```
  await postgres`
    CREATE TABLE IF NOT EXISTS "roles" (
      "id" bigserial PRIMARY KEY,
      "name" text NOT NULL,
      "permissions" text array NOT NULL
    );
  `;
```

- INSERT:

```

  const [example_role] = await postgres`
    INSERT INTO "roles" (
      "name",
      "permissions"
    ) VALUES (
      ${'Example Role'},
      ${postgres.array(['example_permission_1'])}
    ) RETURNING *;
  `;
  console.log({ example_role });
```

- RESULT

```
  example_role: {
    id: '1', // why is this string now, it was previously an integer?
    name: 'Example Role',
    permissions: [
      'example_permission_1',
    ]
  }
```

**Comment by Minigugus** [comment]
You have to explicitly pass the `postgres.BigInt` builtin custom type in options:

```js
const sql = postgres({
  types: {
    bigint: postgres.BigInt
  }
});
```

then `bigserial` are properly decoded as BigInt:
```js
  example_role: {
    id: 1n,
    name: 'Example Role',
    permissions: [
      'example_permission_1',
    ]
  }
```

and for encoding
```js
sql.types.bigint(yourBigint)
sql.types.bigint(42n)
```

That' s because `bigserial` supports 64-bit integers but JS numbers do not, which can lead to potential bugs in production. Also, Node's BigInt support is quite new (ES2020), so you need to define it explicitly.

**Comment by joshxyzhimself** [comment]
@Minigugus thanks a lot!
