### ISSUE TITLE
Logging Queries

### ISSUE THREAD

**Issue by spacejack** [porsager/postgres#113]
It would be nice to have a way to capture the final SQL query string and parameters. For example, pg-promise has the following option:

```
const pgp = PGP({
    query: e => {
        console.log('query:', e.query)
        if (e.params) {
            console.log('params:', e.params)
        }
    }
})
```

**Comment by TobiasNickel** [comment]
It can be handy, But I would think this would belong into userland, not into the driver. In the readme, you see the best practice of making a db.js module. instead of expory the postgres sql directly, you can export a wrapper:

```js
// db.js
const postgres = require('postgres')

const sql = postgres({ ...options }) // will default to the same as psql

const lastQuery = {};

module.exports = function(sqlParts, ...params){
  lastQuery.query = sqlParts.join(?); // can be more smart with $1, $2,... $n
  lastQuery.params = params;
  return sql(sqlParts, ...params);
}

module.exports.getLastQuery = function(){ return {...lastQuery}; };
```

on this code sample, you might see, that there are more decisions to make. is the last query the last requested, or the last finished. does it need to be cloned? some other user would not only need the last, but everything during a script, or during a period of time. ....

So best is to implement yourself. maybe you want to publish your solution as a separat npm package? then others can also profit from what you build.

**Comment by Minigugus** [comment]
@TobiasNickel The problem with this approch is that queries and parameters parsing might be broken if there is an breaking change in `postgres`. Also, the part `lastQuery.query = sqlParts.join(?); // can be more smart with $1, $2,... $n` is more complex than you expect: [`postgres` do a more complex transform of the query than just `$1` in ```sql`INSERT INTO users ${sql(users)}`;```](https://github.com/porsager/postgres/blob/3aacc4026edfb2f1c2f2a68ff8595a79793b2c03/lib/index.js#L453-L463). Morerover, query text and parameters transformation is synchronous, and it [seams possible to do the transformation](https://github.com/porsager/postgres/blob/3aacc4026edfb2f1c2f2a68ff8595a79793b2c03/lib/index.js#L395-L412) before returning [the query promise](https://github.com/porsager/postgres/blob/3aacc4026edfb2f1c2f2a68ff8595a79793b2c03/lib/index.js#L168-L187), in order to be able to do the following for instance with a simple commit in `postgres`:
```js
export default function sqlWithQueryLogger(sqlParts, ...params) {
  const query = sql(sqlParts, ...params);
  console.info('QUERY:', query.query, query.params);
  return query;
}
```
It can simplify query timing without loosing correctness.

I also noticed when writing this message that [the query text and parameters are evaluated asynchronously](https://github.com/porsager/postgres/blob/3aacc4026edfb2f1c2f2a68ff8595a79793b2c03/lib/index.js#L209), so the following code, with the current version of `postgres`, returns `INSERT INTO test (a) VALUES ($1);` not `INSERT INTO test (a, b) VALUES ($1, $2);`:
```js
const user = { a: 'an, b: 'example' };
const query = sql`INSERT INTO users ${sql(user)};`;
delete user.b;
const { command } = await query;
return command;
```
Therefore, a correct userland implementation of the query text transformation would have to be asynchronous.

**Comment by xiaoyu-tamu** [comment]
Connection options accept debug function that will receive connection, query, params

**Comment by spacejack** [comment]
> Connection options accept debug function that will receive connection, query, params

Thank you! That seems to work.
