### ISSUE TITLE
Expose possibility to create prepared queries manually

### ISSUE THREAD

**Issue by stalniy** [porsager/postgres#122]
## Description

I have a separate library that converts JSON objects into WHERE condition. This library produces a raw SQL string with placeholders inside (i.e., `name = $1 and active = $2`). So, it prevents possibility of SQL injection. I want to use objects for WHERE conditions because I need to allow clients of my API to send object queries like this:

```js
const query = {
  firstName: 'John',
  age: { lt: 12 }
};
```

To merge `postgres` with that library, I use `sql.unsafe` which is safe for my use cases. But **what I miss is the possibility to create prepared statements for this dynamic queries** (I have no more than 10th of them and usually 3-5 are used very often)

## Desired behavior

Please, expose possibility to make prepared queries manually.

**P.S.**: thanks for the awesome library, I really like it!

**Comment by Johnson444** [comment]
use can use this in the meantime: https://www.npmjs.com/package/postgres-partial

**Comment by stalniy** [comment]
@porsager what is your opinion on this issue? Will you expose possibility to manually specify that unsafe query should be prepared?

**Comment by stalniy** [comment]
@porsager may I send a PR that exposes an option to use prepare statements for `unsafe` query? As far as I can see from `index.js` it should be a simple change

**Comment by porsager** [comment]
Yeah, how do you imagine the API ? :)

**Comment by stalniy** [comment]
I thought we could use generated SQL as a key for prepared statement, written once in the code it doesn't change, so we just need a way to make that query prepared:

```ts
await sql.unsafe("SELECT $1", [true], { no_prepare: false })
// or 
await sql.unsafe("SELECT $1", [true], { prepare: true })
```

But I don't know the details of how prepared statements work in Postgres, so if I miss something obvious, please let me know :)

**Comment by porsager** [comment]
Ah no, you're right, of course we just id by the query string. My head is deep in another tagged template project where the unique invocation site mattered.. 

We could even enable it by default, but I think a reason for not having it enabled by default should be because there's a greater chance of creating too many prepared statements due to the nature of unsafe being used for highly dynamic queries? 

Maybe there's an idea for library authors to be able to specify a specific id themselves, so it could be boolean | string? It's just a thought, I'm fine starting out with just boolean.

I think `prepare: true` is best if we later wan't to introduce `string`.

**Comment by stalniy** [comment]
Awesome! 

Yes, it's better to have prepared statements to be disabled by default for `unsafe`  method. 

In general, I prefer direct logic/thinking instead of negated, that's why I like `prepare: string | boolean` more but there is already `no_prepare` option for `postgres` factory. So, either we need to be consistent or deprecate `no_prepare` and replace it with `prepare`. What are you thoughts on this?

**Comment by porsager** [comment]
I agree. Let's deprecate `no_prepare` and make it `prepare: true` by default.
