### ISSUE TITLE
Typescript types not working

### ISSUE THREAD

**Issue by SwanX1** [porsager/postgres#137]
When I try to import the package using `import postgres from "postgres";`, this error appears:
```
Could not find a declaration file for module 'postgres'. 'project/node_modules/postgres/lib/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/postgres` if it exists or add a new declaration (.d.ts) file containing `declare module 'postgres';` ts(7016)
```
I've tried to add `@types/postgres` as a dependency, however it does not exist. I've also tried to add `"allowSyntheticDefaultImports": true` to my `tsconfig.json`, as mentioned in #124 to no avail.

I am using Node: v12.16.3, TSC: 4.1.3

How do I import this package with TypeScript?

**Comment by Minigugus** [comment]
TypeScript definitions are available since version 2, which is still in beta. Make sure to use the `beta` version of this lib (just reinstall this lib with a `@beta` after the package name: `npm install postgres@beta` or `yarn add postgres@beta`) :wink:

I know it's not easy to use the TypeScript definitions of this lib, but there's nothing more we can do :disappointed:

**Comment by joaopaulobdac** [comment]
> but there's nothing more we can do

I just ran into the same isse as #85 (TypeScript doesn't let me do `INSERT INTO thing ${sql(newThing)}`).
But since 2.0 will be a major version change and it's still in beta, should we break up the `sql` function into two functions `sql` and `helper` to fix this? Otherwise, this feature would be unusable with TypeScript.

@porsager Maybe you should give your opinion on this suggestion

**Comment by porsager** [comment]
@Minigugus is the types easy to use when v2 is released? I might be ok adding devDependencies if that improves things.

@joaopaulobdac So if i understand correctly this is a limitation of Typescript? We could consider adding explicit methods for serialization then (eg. sql.identifier, sql.keyword)? I'm not sure how that lines up for my composition ideas for v2 with ```sql`` ```, but hopefully I've got time to look at that soon.

**Comment by Minigugus** [comment]
@porsager The only need for a `devDependency` is to add correct types to the `ssl` option, to link it to the NodeJS types.

Also, #84 is still pending, maybe it should get merged before the v2 release? I don't know when you plan to release the v2 but maybe #84 should be merged while still in beta so that we can check types are fine for most users?

**Comment by porsager** [comment]
Oh man, sorry, that's not on purpose. I'll merge right away, and do a new beta release.

**Comment by porsager** [comment]
@Minigugus If i understand correctly we can still do fine without a devDependency, so this can be closed?
