### ISSUE TITLE
when joining two tables, columns with the same names conflict and only one of them is returned

### ISSUE THREAD

**Issue by MassiveFermion** [porsager/postgres#173]
Consider the following scenario:
```
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,

    PRIMARY KEY ("id")
);

CREATE TABLE "Post" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "content" TEXT,
    "published" BOOLEAN NOT NULL DEFAULT false,
    "authorId" INTEGER NOT NULL,

    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "User.email_unique" ON "User"("email");
ALTER TABLE "Post" ADD FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
````

Now consider we run the following code:
```
sql`select * from "User" as u join "Post" as p on p."authorId"=u.id where u.id=1`.then(console.log)
```
The result will be something like below:
```
[
  {
    id: 2,
    email: 'alice@prisma.io',
    name: 'Alice',
    createdAt: 2021-04-13T08:26:37.738Z,
    updatedAt: 2021-04-13T08:26:37.739Z,
    title: 'Hello World',
    content: null,
    published: false,
    authorId: 1
  },
  count: 1,
  command: 'SELECT'
]
```
As you can see, there is only one id field, which means we don't have the id of either the user or the post. Of course we have authorId but this is only a coincidence that the field with the same name is the foreign key. But any field that is not the foreign key but has the same name in the two tables will be lost.
Its possible to give the fields aliases to solve this problem but that means we can't use `select *` and should list each and every column that we need which can get really cumbersome as the number of columns grow.
So I think this example clearly demonstrates that this method of representing the result is inadequate. For an example of a method that doesn't have this problem, I ran the same query using [postgrex](https://github.com/elixir-ecto/postgrex) and this is the result:
```
%Postgrex.Result{
  columns: ["id", "email", "name", "id", "createdAt", "updatedAt", "title",
   "content", "published", "authorId"],
  command: :select,
  connection_id: 172,
  messages: [],
  num_rows: 1,
  rows: [
    [1, "alice@prisma.io", "Alice", 2, ~N[2021-04-13 12:56:37.738000],
     ~N[2021-04-13 12:56:37.739000], "Hello World", nil, false, 1]
  ]
}
```
As you can see no data is lost. But to be honest I'm not an advanced enough developer to actually suggest anything, I'm just offering my observations. I should say that [pg](https://github.com/brianc/node-postgres) and [prisma](https://github.com/prisma/prisma)(I think prisma uses its own driver, but I'm not sure) have the same problem which weirdly means (as far as I know) there is no well known postgres driver for node.js that doesn't have this problem!

**Comment by porsager** [comment]
The decision to map the result to JS objects like this was for several reasons. 

1. In real applications you should never use `select *`[0]. I'd always prepare the result properly in sql. So in your example for instance, I'd do like this while developing (later I'd specify specific columns for user and posts):
```sql
select 
  u.*,
  json_agg(p) as posts
from "User" as u 
join "Post" as p on p."authorId"=u.id 
where u.id=1
group by u.id
```

This would give you the following result:
```js
{
  id: 1,
  email: 'murray@rothbard.com',
  name: 'Murray',
  posts: [
    { id: 1, title: 'Some title', ... },
    { id: 2, title: 'Another title', ... }
  ]
}
```

2. The PostgreSQL protocol only returns the table oid, not the name in RowDescription, so there would be unnecessary overhead to actually show tablename + column when you have column name collisions. As you can see in your postgrex example, the only way to know which table `id` at index 0 and `id` at index 3 it belongs to is to implicitly infer it from the order you join your tables in the actual query. This also means you can't change your query in the future without also changing the handling of the result.

3. I think the result is the idiomatic way to handle data in js, and since it actually encourages good sql at the same time I think it's a good solution.


Now there has been talk about exposing an option to receive the result where rows are arrays (like postgrex), and I'm not opposed to that, but you can also shape your result like that in sql, so I haven't seen it as high priority.

I hope that gives you a good idea for the reasoning behind the result, and some ways to move on using Postgres.js 😉

[0] (there are many reasons for this which you can google your way to)
