### ISSUE TITLE
Support for PG connections

### ISSUE THREAD

**Issue by jadbox** [porsager/postgres#178]
Hey folks, I currently have a large project where some parts of using `pg` library and other parts are using `postgres`. Since both make connections to the DB and use pooling, is there a way that I can specify to `Postgres` lib to use the connection pool that the `pg` library exposes?

OR, is it possible to use the `sql` function to generate for me just the query that I can then feed directly to `pg`'s Query to execute?

**Comment by porsager** [comment]
Hi @jadbox .. Sorry, I had missed your issue here. It's an interesting situation. 

Did you find a solution?

I don't think it would make sense for Postgres.js to support node-pg connections as such, but perhaps you could mock `pg` instead to use Postgres.js with `sql.unsafe`. Depending on your project and abstractions I imagine it could be fairly straight forward. 

If you're still looking for a solution, pop into the [Postgres.js gitter](https://gitter.im/porsager/postgres) and I'll see if I can be of any help.
