### ISSUE TITLE
extra dynamic queries

### ISSUE THREAD

**Issue by basaran** [porsager/postgres#244]
Hi again :)

Could you please advise the possibility of achieving this? or if it at all feasible to do?

```js
const key = "yay";
 
const query = `
   SELECT * from ahoy
   WHERE 1 = 1
   ${key && `AND ahoy_key = '${key}'`}
`;
```

**Comment by basaran** [comment]
Besides the `unsafe` way that is.

**Comment by porsager** [comment]
Hey there 🙂

Dynamically composing sql like that is not possible yet, but I've got a plan outlined and the progress is tracked in #12 

The reason it's not simply concatenating strings is because I want to prevent accidental sql injection. 

Usually there are ways of achieving it without resolving to `.unsafe()`, for instance your case above could be written like this:

const key = "yay"; // or null
 
const query = `
   SELECT * from ahoy
   WHERE 1 = 1 and (${ key } is null or key = ${ key })
`;

**Comment by basaran** [comment]
hi, your example is giving me:

```
could not determine data type of parameter $1
```

am I missing anything?

**Comment by basaran** [comment]
`${key}::text` worked however. Thank you,

**Comment by porsager** [comment]
Ah ok. Out of curiosity what type is the ahoy_key column in your example?

**Comment by basaran** [comment]
it was just a character varying.

```
const key = false || null
```

was also fine, with `::text`

**Comment by porsager** [comment]
Ah alright, thanks 👍

**Comment by basaran** [comment]
well, thank you kind sir :)

Here's the complete snippet for the future trouble maker:

```js
const key = "/2212" || null;
//const key = false || null;

const result = await sql`
    SELECT * from ahoy
    WHERE 1 = 1
    and (${key}::text is null or ahoy_key = ${key})
`;
```

**Comment by arxpoetica** [comment]
I've got a query with this:

```sql
WHERE lower(tt.tags::text)::text[] @> ${sql.array(tags)}
```

It works great when there's a tag string or more in the array. But when `sql.array(tags)` is `[]` it only returns items with something tagged. I need to return all results searching against an empty array.

`1=1` is doing nothing for me.

Would really like to avoid `unsafe`. Help?

**Comment by arxpoetica** [comment]
Hey! This worked:

```sql
WHERE lower(tt.tags::text)::text[] @> ${sql.array(tags)}
	OR ${sql.array(tags)} = '{}'
```
