### ISSUE TITLE
Syntax error when using intervals

### ISSUE THREAD

**Issue by PierBover** [porsager/postgres#247]
For some reason this query works fine:

```
SELECT
n - interval '1 hour' AS start_time,
n AS end_time
FROM generate_series(now() - INTERVAL '24 hours', now(), '1hour') n
```

But when using dynamic parameters I get the `syntax error at or near "$1"` error.

```
const unit = '1 hour';
const interval = '24 hours';

const result = await sql`
SELECT
n - interval '1 hour' AS start_time,
n AS end_time
FROM generate_series(now() - INTERVAL ${interval}, now(), ${unit}) n
`;
```

I tried using the `sql()` function instead:

```
FROM generate_series(now() - INTERVAL ${sql(interval)}, now(), ${sql(unit)}) n
```

But I got the error `Error: syntax error at or near ""30 days""`.

Is this a bug or am I missing something very obvious?

**Comment by PierBover** [comment]
I also tried using `::interval` as [suggested here](https://github.com/brianc/node-postgres/issues/1593#issuecomment-373547556):

```
FROM generate_series(now() - INTERVAL ${interval}::interval, now(), ${unit}::interval) n
```

But I still got the `syntax error at or near "$1"` error.

**Comment by PierBover** [comment]
The solution was using `CAST`:

```
FROM generate_series(now() - CAST(${interval} AS INTERVAL), now(), CAST(${unit} AS INTERVAL)) n
```

**Comment by porsager** [comment]
Hi @PierBover 

Thanks for the follow up.

I usually do 
```js
const someNumber = 1
await sql`select ${ someNumber + 'hour' }::interval`
```

**Comment by PierBover** [comment]
Thanks @porsager that's the best solution :)

Why doesn't `INTERVAL ${interval}` work but `${interval}::interval` does?

**Comment by porsager** [comment]
It's because Postgres.js sends them as arguments to the query and replaces their position by `$1, $2, ...`. This way PostgreSQL takes care of handling them correct so that eg. no sql injection is possible, and casting them to the proper types if defined. Now PostgreSQL query arguments are only allowed in place of data values, and in the case of `INTERVAL '1 hour'`, `'1 hour'` is not a data value, which is the same reason you also natively can't do `SELECT INTERVAL ('1' || ' hour');`.

Now the next question obviously becomes why the string coming after INTERVAL is not a data value. That I don't know, but my suspicion is that it's something about `INTERVAL ...` coming from the SQL standard and not fitting into the rules PostgreSQL has for data values.

**Comment by uasan** [comment]
You may be wondering, in future JS releases, there will be native support for intervals [Temporal.Duration](https://tc39.es/proposal-temporal/docs/duration.html)
There is already a polyfill and it makes sense to support this data type at the postgres client level )

**Comment by PierBover** [comment]
Thanks a lot for the explanation @porsager . Much appreciated!

**Comment by emerleite** [comment]
Please, update it on DOCs. Spent hours figuring out how to work with INTERVALS.

**Comment by porsager** [comment]
You're welcome to make a PR @emerleite
