### ISSUE TITLE
BUG: Inserting with js object causes undefined values for fields

### ISSUE THREAD

**Issue by jadbox** [porsager/postgres#285]
Pg version: v3

When inserting with an object, all the values become undefined values.

```ts
var params: any = {
		tid: symbol,
		uid,
		name: name,
		total: amount,
		img,
		isnft: true,
		descr: '',
	};
const [r] = await sql<any[]>`insert into tokens ${sql(params)} returning *`
```

Result:
```sql
insert into tokens ("tid","uid","name","total","img","isnft","descr","brand","attributes")values(undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined) returning *
```

**Comment by jadbox** [comment]
Can confirm that the above code works in the lib v2.

**Comment by porsager** [comment]
Hi @jadbox .. That's odd, I'm not able to repro here - can you post the options config your have in `postgres(...)`?

**Comment by jadbox** [comment]
@porsager sure thing:

const sql = postgres(`postgres://${PGUSER}:${PGPASS}@${PGDOMAIN}:5432/mydb`, { debug: true });

I don't think it matters but I'm using postgresql v14.

**Comment by porsager** [comment]
Hi @jadbox, unfortunately still not able to reproduce - can you maybe post a full repro sample?

**Comment by jadbox** [comment]
@porsager I'll see what I can do, but it may take me a few days to circle back to this and try to provide more detailed context. If it helps, here's the function I'm using for `debug` when connecting. The function is to trace out all queries on the server. Maybe this is the cause from v2 to v3?

```ts
const debug = (connection, query, params) => {
	if (ISDEV && process.env.NODE_ENV !== 'test') {
		let values = params.map(x=>x.value);
		values.forEach( (x, i) => {
			if(typeof values[i] === 'string') values[i] = `'${values[i]}'`;
			query = query.replace(`$${i+1}`, values[i]) 
		});
	 	console.log('q?', query);
	}
};
```

**Comment by porsager** [comment]
Ah, so the query is actually executed correctly with the correct values, you're just logging something as per the v2 debug signature, which doesn't work :) I was pulling my hair out trying to understand how the parameter placeholders could turn into `undefined` 😂

In v3 the debug signature is `(connection, query, params, types)` where params is an array of the values, not an object with { value }. `types` is an array of the oid types.

For logging queries I would simply suggest doing `debug: console.log` instead of your function above. Replacing the placeholders with the values just seems confusing as it's not possible to know how they're escaped (the db handles that), so looking at the logged query will give you false assumptions about what's going on.
