### ISSUE TITLE
CONNECTION_CLOSED error on listen()

### ISSUE THREAD

**Issue by PierBover** [porsager/postgres#310]
I'm getting this error kinda randomly:

```
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: write CONNECTION_CLOSED undefined:undefined
    at Socket.closed (file:///.../node_modules/postgres/src/connection.js:448:57)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at TCP.<anonymous> (node:net:687:12)
    at cachedError (file:///.../node_modules/postgres/src/query.js:160:23)
    at new Query (file:///.../node_modules/postgres/src/query.js:36:24)
    at sql (file:///.../node_modules/postgres/src/index.js:104:11)
```

I'm not sure if I should do anything to handle it myself, but I'm posting the issue since the docs mention:

> This should not happen during normal operations, so please create an issue if this was unexpected.

**Comment by porsager** [comment]
Exactly. Thanks for reading that long in the docs, and I'm indeed happy you created this issue ;)

Do you have some details about how long after service start you're seeing this and how long idle time you have between `notifies`? This could be something closing the tcp connection either due to it being idle (not related to keepalive), or perhaps a max duration a tcp connection can be open. Do you connect to the db directly or through a proxy or eg. pgbouncer?

**Comment by PierBover** [comment]
The time seems very random.

When I opened this issue it happened after maybe 30 mins of inactivity. But the same service has been running for a couple of hours of inactivity now without the error. Even when I sleep my machine (the service is running locally).

I'm connecting to a PG instance running in Fly.io through Wireguard.

I don't think they are using PgBouncer... but this is the Docker instance config running PG:

https://github.com/fly-apps/postgres-ha/blob/main/Dockerfile

**Comment by porsager** [comment]
Ah, I think this could be related to HAProxy being in the middle.. So perhaps tcp keep alives are not forwarded, which results in the PostgreSQL server closing the connection. Now for the `listen` use-case the best would be to not having to do reconnects during normal operation. I think just doing a single message over the wire to keep the connection alive is better than suffering a reconnect and potentially missing notifies.

This is the exact reason why I've kept throwing this error instead of ignoring it and doing a simple reconnect, because that could hide deeper problems.

In this case the HAProxy is probably configured to not have long running tcp connections so that load balancing can work better. This is great for everything but our `listen` case where we indeed would like to keep an open connections ready to receive notifies at all times.

**Comment by PierBover** [comment]
I agree ideally there should be no reconnects, but since the connection could drop at any moment I just get any pending stuff in the queue jobs table on reconnect (with the new handlers you added).

But I do need to handle this error in some way. Otherwise the listen() client just dies and that's much worse than losing a couple of notifications between reconnects.

Right now I'm doing something like this:

```
await sql.listen(
  'NEW_JOB_UPDATE',
  onJobMessage,
  getPendingJobs
);
```

I really have no idea where I can catch the exception though...

**Comment by porsager** [comment]
@PierBover I'm trying to replicate this myself, but without luck. Are you sure this could not be from a query you are not catching errors on?

**Comment by PierBover** [comment]
I will add a couple more try/catch statements to be 100% certain but I really don't think it's an issue with the queries.

Another clue is the error happens when nothing is really going on in the application (since I'm the only user for now and it's running locally).

I think the main problem here is not so much that it disconnects, but that there's no way to catch errors from the listen function.

**Comment by uasan** [comment]
> I think the main problem here is not so much that it disconnects, but that there's no way to catch errors from the listen function.

Do you need the fourth optional argument `onError` to the `listen` method?

**Comment by PierBover** [comment]
> Do you need the fourth optional argument `onError` to the `listen` method?

I guess that would work.

Then I could restart the listen() function instead of my subscriptions just dying.

**Comment by uasan** [comment]
It will work if you guarantee to handle loss of client connection, without some kind of ping pong mechanism it will be difficult to handle all cases, so you have two problems )

1. extend the interface of the listem method
2. find a reliable ping pong mechanism

**Comment by PierBover** [comment]
> extend the interface of the listem method

Even if I did that, I think there's no way my error handler would catch the listen() errors. These are handled internally which is the whole problem.

> find a reliable ping pong mechanism

Why would I need that? If the connection dies I would just simply reconnect. It's what I've been doing with `node-pg` and it has worked flawlessly.

**Comment by uasan** [comment]
> Why would I need that? If the connection dies I would just simply reconnect. It's what I've been doing with node-pg and it has worked flawlessly.

I mean, the author of the library needs this mechanism, he needs it at the TCP socket level and / or postgres protocol parameters, there are many options for configuring TCP sockets and many parameters at the postgres protocol level...

**Comment by PierBover** [comment]
> I mean, the author of the library (@porsager ) needs this mechanism, he needs it at the TCP socket level and / or postgres protocol parameters, there are many options for configuring TCP sockets and many parameters at the postgres protocol level...

Ah right sorry, I thought you were to me 😂

**Comment by porsager** [comment]
The issue here "if the unhandled error is thrown from the listen connection" is simply that we're not reconnecting

**Comment by porsager** [comment]
I'll dig some more at my end too 😊

**Comment by PierBover** [comment]
@porsager I have a bit more info.

The error is happening in the new `onlisten` handler you added.

So I have something like this:

```
sql.listen(
  'SOMETHING',
  onMessage,
  onlisten
);

async function onListen () {
  try {
    await sql`select * from table`;    
  } catch (error) {
    // error is caught here
  }
}
```

In the meantime, I've done this:

```
async function onListen () {
  try {
    await sql`select * from table`;    
  } catch (error) {
    // error is caught here
    initSubscription();
  }
}
```

I'll let you know how it goes.

**Comment by porsager** [comment]
Perfect. That makes sense! The error is not coming from the listener connection, but from your query in the onlisten function. The reason that happens is most likely because the tcp connection that query uses is half closed, so it first errors when the query is executed and Postgres.js tries to write to the half closed socket. 

This means it is not related to onlisten directly, but only happens in tandem because the timeouts match for the two connections. 

Now we could consider to build in retrying queries once on this specific error, which would also be an improvement for other queries bumping into half closed sockets. 

A solution for you for now will be to set `idle_timeout: 120` (2 minutes).

**Comment by porsager** [comment]
Postgres.js already retries queries once if a prepared statement is invalidated so I feel pretty confident that adding retry here too would be a great solution.

**Comment by porsager** [comment]
You can of course also solve it by catching the error yourself and doing your own retry.

**Comment by porsager** [comment]
> In the meantime, I've done this:

That will result in duplicate calls to onMessage, so you should rather do:

```

async function onListen () {
  try {
    await sql`select * from table`;    
  } catch (error) {
    await sql`select * from table`;
  }
}

```

**Comment by PierBover** [comment]
Maybe I'm mistaken but I thought that using `sql` was some kind of pool that creates clients on demand, retries queries, etc?

I have only seen this error when using listen(). Regular queries have been working fine and I have never seen this `CONNECTION_CLOSED` error.

I'll try with the `idle_timeout` setting and let you know how it goes.

**Comment by porsager** [comment]
> Maybe I'm mistaken but I thought that using `sql` was some kind of pool that creates clients on demand, retries queries, etc?

No, that's correct, but it creates connections in the pool lazily, and there is only retry for invalid prepared statements. So it doesn't retry other queries individually, but it reconnects automatically. 

> I have only seen this error when using listen(). Regular queries have been working fine and I have never seen this `CONNECTION_CLOSED` error.

Yes, that's what i meant with:
> This means it is not related to onlisten directly, but only happens in tandem because the timeouts match for the two connections.

So let's say your service only has this listen setup - it will first create a dedicated connection for listening, and it will then open a connection in the pool once you execute your query in onlisten. Those two connections will open almost at the same time. Let's say the server you connect to closes connections without a FIN packet after 10 minutes. The listen connection will then close after about a minute because it never gets a tcp keepalive response. That will make listen reconnect, then it calls your onlisten function, and now you're about to execute a query again. Postgres.js will look in the connection pool and see a connection that appears to be open (it cannot know it was half closed because the keepalive timeout was not reached yet), so it will try to write to that socket, which will then throw an error because no ack is received. This is why having an idle_timeout setting lower than the server will solve the problem. Instead of the connection ending up as half open, Postgres.js will close it after idle_timeout, and when you make your query a new connection will be opened instead. 

> I'll try with the `idle_timeout` setting and let you know how it goes.

Cool. Let me know how that goes 😊 I cannot imagine the haproxy has a max lifetime on the connection instead of idle, but if it does you can also look at setting max_lifetime. 

Apologies for mistakes, this was written on my phone.

**Comment by PierBover** [comment]
So far the `idle_timeout` solution has been working great.

Off topic but it would be great if there was some sort of verbose mode that would print stats to the console like how much timeout happened on every query, etc.

I'll run this for a couple of days and let you know how it goes.

**Comment by porsager** [comment]
Ok, so to sum it up, the uncaught error was coming from the query inside onlisten most likely due to a half open tcp socket. Nothing inside Postgres.js was throwing uncaught errors.

A way to avoid periodic half open sockets with servers that doesn't respect the tcp keep alive setting and closes sockets after a certain timeout is to set `idle_timeout` lower than the servers timeout. That way Postgres.js avoids stumbling over half open sockets.

That doesn't prevent the error from happening in other circumstances since it could also happen due to network failures etc. so I suggest adding 2 solutions to prevent that. First off, if a query fails with connection_closed on write, we retry the query once to allow the connection to reconnect. Also I suggest adding a method to make it really easy to retry a query `n` times with an optional delay in between like:

```
const retries = await sql`...`.retry(retries, delaySeconds)
```

About a verbose mode, then yes, could probably be useful, but it's not really something I need myself, so I won't put time into myself .

I'll close this issue ;)

**Comment by PierBover** [comment]
I've been experimenting and it seems the sweet spot for my situation is `idle_timeout` to be 30 seconds.

Less than that, and I don't see the `CONNECTION_CLOSED` error but I do see `CONNECT_TIMEOUT` error although much less often. With 30 seconds I have a service that has been running for a couple of days without issues.

Thanks for your support @porsager !

**Comment by porsager** [comment]
You're welcome, thanks for the debugging ;) 

About `CONNECT_TIMEOUT` error you can increase the connection timeout using `connect_timeout` option which is 30 seconds by default.
