### ISSUE TITLE
Question: Does `sql.listen` reconnect?

### ISSUE THREAD

**Issue by lukeed** [porsager/postgres#35]
Hey, as the title says, I'm wondering how any errors within `sql.listen` are handled or _should be_ handled. Since there's no Pool and connections are created lazily (except for `sql.listen`) I'm curious what the approach here should be.

Thanks!

**Comment by porsager** [comment]
That's a very nice observation @lukeed !

Currently there's no "out of bound" error handling or reconnect on sql.listen. 

It should definitely reconnect automatically!

The initial `sql.listen` call for a channel will return the promise from the actual query sent. `sql.listen` will then only throw if there's a connection error initially or an error in the channel name. That means we should be able to reconnect automatically if the initial query succeeded since the connection and channel name should work.

I can't think of any errors that would be of interest on the listener connection except for those related to `listen` queries. Can you?

**Comment by lukeed** [comment]
:) I'm thinking of standard pooling arrangements. It's somewhat straightforward to attempt new connections until an initial `sql.listen` succeeds. But if the Postgres server dies (after listening) there doesn't seem to be an easy way to be aware of that and/or start listening again once the DB comes back up.

**Comment by porsager** [comment]
Right, I think `postgres` could handle that by automatically reconnecting the listener connection if any listeners were added, but I guess you still might want to be aware of that situation in userland, if for instance the server doesn't come up within a reasonable amount of time...

I've got a little test with a reconnect on close implementation here..
https://github.com/porsager/postgres/commit/5c9687529b87a0a18b5f777080f993d6a01e4a09
Would probably need some kind of backoff / timeout for the reconnect

**Comment by FrigoEU** [comment]
Hey @porsager,

Thanks for all the work on this! The package works really well. I've been trying out this reconnection functionality and found that some errors (the one I found is ECONNRESET, when I kill the database server manually) the onclose handler of the connection doesn't get called. Reason is that in the onclose of the postgresSocket, the error is an instance of Error and so it doesn't call close() but it calls error().

I can make a PR for this, but I'm not sure if this is intentional?

Simon

**Comment by porsager** [comment]
Hi @FrigoEU that sounds like a bug, so thanks a lot for bringing it up, I'll try to see if I can reproduce :)

**Comment by FrigoEU** [comment]
Thanks for the quick response! 

How I reproduce it:
1. Set a console.log in the onclose function of postgresSocket
2. Start a connection (eg: set up a .listen session)
2. Stop postgresql
3. I get a few errors in sequence: "PostgresError: the database system is shutting down", then "Error: write CONNECTION_CLOSED localhost:5432", then Error: "read ECONNRESET"

**Comment by uasan** [comment]
Yes, this problem is reproducible if the connection was terminated externally.
In this case (if there are listeners) the client should automatically reconnect.

**Comment by porsager** [comment]
Yeah, I'm currently improving the connection handling, and should have a fix up for this and a couple of other issues today / tomorrow.

**Comment by uasan** [comment]
@porsager, any update progress?

**Comment by porsager** [comment]
@uasan I ended up in a pretty deep rabbit hole with these changes, since I was also doing improvements to the multi host failover connections and backoff with retries. The current connection implementation needed a touch up to handle these cases properly, but I'll see if I can backport a fix for this specific issue for now...

**Comment by porsager** [comment]
Would you mind giving https://github.com/porsager/postgres/tree/listen-reconnect a shot?

**Comment by uasan** [comment]
Ok, I testing this branch

**Comment by uasan** [comment]
@porsager We tested this branch, it fixes this bug... 👍
When are you planning to merge this branch to master?

**Comment by porsager** [comment]
That's great to know @uasan - thank you.
I'll merge and release a new beta today..
