### ISSUE TITLE
PostgresError: unrecognized configuration parameter "schema"

### ISSUE THREAD

**Issue by divyenduz** [porsager/postgres#367]
This is happening in `3.2.0` and versions above it. Version `3.1.0` works fine. 

To reproduce, use a connection string with schema

```ts
import postgres from 'postgres'

async function main() {
  const sql = postgres(`postgresql://postgres:postgres@localhost:5432/trackfootball_dev?schema=public`)
  await sql`SELECT 1`
}
main()
```

With `3.1.0` this snippet works, with 3.2.0 (and onwards versions), it fails with `PostgresError: unrecognized configuration parameter \"schema\""`

**Comment by porsager** [comment]
Hi @divyenduz .

That was a bug in 3.1 which didn't forward extra url params to PostgreSQL, so having `schema=public` in your url actually didn't do anything before (but worked because public was most likely first in the default search_path of your db).

Now you should use the correct property to set the search path, which in your case would be `search_path=public`.

**Comment by divyenduz** [comment]
Thank you, @porsager

You are right, I was under the impression that `schema` is a connection parameter but it is not https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
