### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by codergautam** [porsager/postgres#369]
Hello, I'm new to postgres and everything, but I've noticed that it uses too many connections. I was assuming that one node process = one database instance. I'm using a singleton pattern to set up the database, like this:

```
const postgres = require("postgres");

const sql = postgres(process.env.DATABASE_URL, {ssl: {rejectUnauthorized:false}});
console.log("Connected to database");
module.exports = {sql: sql};
```

This way I can import this file in any other file to use the sql function. I noticed that even with 3ish processes, I get 16 connections. Is this expected, or is there any way to fix this?

![image](https://user-images.githubusercontent.com/66850133/168802886-db196621-fd9e-47fa-a7db-3ed2238ee4da.png)

**Comment by codergautam** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/66850133/168915767-8939e5b2-3e28-4b37-92fe-0cb7704f6c31.png">

**Comment by codergautam** [comment]
I see that each query is it's own connection. How do I terminate a connection then?

**Comment by codergautam** [comment]
I checked the "idle" connections, and saw that many Ips are there multiple times. How do I make sure one process only has one connection.
<img width="97" alt="Screen Shot 2022-05-17 at 4 51 45 PM" src="https://user-images.githubusercontent.com/66850133/168916372-fdd177a1-ac63-4590-8860-d0f08b268b74.png">

**Comment by porsager** [comment]
Hey @codergautam 👋 

That is expected.

Postgres.js has a default setting of using up to 10 connections per instance. That's usually a good default for most things, but also something you will often want to configure depending on your needs. 

PostgreSQL only handles 1 query on a connection at a time even though you can queue several (pipelining). Imagine you have a query that takes 5 seconds to finish. If you have 2 queries being executed on the same connection at the same time, the query which comes first will finish in 5 seconds, but the second query will finish in 10 seconds because it has to wait for the other query. Now if you allow having more connections open you can finish both queries in 5 seconds. 

With the `max` option (default: 10) you can specify what the max number of concurrently open connections should be. Postgres.js will then open up to that amount every time a query is made if there are no open connections available to execute the query on.

You can set `max: 1` if you only want one connection open per instance, but the fact that you see the counts `7, 8, 4` means that there have been times where up to that many queries have wanted to execute concurrently. If you set max to one you can expect those cases to respond slower for some users. Let's imagine the case where 8 connections were open. If your general query takes 2 seconds, the query that comes last in line will finish in 16 seconds instead of 2. 

You can also set `idle_time: 30` which will close any connections that have been idle for more than 30 seconds, and Postgres.js will then only reopen them again if needed.

I hope that gives you an idea of how to handle the number of connections for each instance. 

Good luck on your Postrges journey 🎉

**Comment by codergautam** [comment]
Ah, that makes so much more sense now. For a second I thought it was a connection leak or something, but I've updated my code with the idle time and max: 5, and it seems to work! Thanks!
