### ISSUE TITLE
why are Result array properties non-enumerable?

### ISSUE THREAD

**Issue by xerosanyam** [porsager/postgres#402]
The result array here defines different properties. https://github.com/porsager/postgres/blob/a9bfd19fc1a620f26d8ad447d40092895052f73c/cjs/src/result.js

by default object.define makes `enumerable=false`,
I feel these properties can be made enumerable as they are part of result. user should be able to list these properties easily using `JSON.stringify(res)`

Else, README.md can be modified by accordingly
 "The Result Array returned from queries is a custom array allowing for easy destructuring ~**_or passing on directly to JSON.stringify_**~ or general Array usage".

**Comment by porsager** [comment]
It's an array so no properties can come out from JSON.stringify 😉 The whole point is that it's basically just an array, and that's why the readme highlights it (no need for a change there). I think you're misunderstanding the purpose of this design. The idea is that you can easily work with the resulting rows from your query. 

If you're interested in the properties like `count` or `command` you can easily access those and use as you please.

It wouldn't change much if these properties were enumerable, but unfortunately it confused newcomers to js more having them enumerable in v1, so that's part of the reason why it was changed (check out https://github.com/porsager/postgres/issues/147)
