### ISSUE TITLE
problem with empty array in where

### ISSUE THREAD

**Issue by massivefermion** [porsager/postgres#417]
At first I should say this is a great postgres client and I really enjoy using it, so thank you very much.
with that out of the way, I have a query that looks like this:
`select * from users where id in ${sql(user_ids)}`
where `user_ids` is an array of integer ids. It works when the array is not empty. But when the array is empty, I get the following error:

> Uncaught PostgresError: syntax error at or near ")"

I expected to just get an empty array as a result. Am I missing something or is it really a bug?
thanks

**Comment by porsager** [comment]
Hey @massivefermion - That's indeed a bug :) The issue is that it generates the following code which is not valid.
```sql
select * from users where id in ()
```

A good solution I think would be to generate the following instead if the array is empty:
```sql
select * from users where id in (null)
```

That should never become true, so it would result in the expectation of returning an empty result array.

**Comment by massivefermion** [comment]
ok, this is how I solved it for now:
`select * from users where id in ${sql(user_ids.length > 0?user_ids:[null])}`
