### ISSUE TITLE
PostgresError: COPY escape must be a single one-byte character

### ISSUE THREAD

**Issue by johndanek** [porsager/postgres#458]
I am trying to execute the following statement using this postgres package:

```
COPY pages (id, status, type, title) FROM '/tmp/ARCHIVE_PAGES.csv' (FORMAT csv, DELIMITER ';', QUOTE '"', ESCAPE '\', NULL '\N');
```

This works fine if I run `psql` locally and enter it via the CLI. But if I use that same command and attempt to execute it like:

```
const pages_results = await sql`COPY pages (id, status, type, title) FROM '/tmp/ARCHIVE_PAGES.csv' (FORMAT csv, DELIMITER ';', QUOTE '"', ESCAPE '\', NULL '\N');`;
```

it fails with the error message `PostgresError: COPY escape must be a single one-byte character`

What is happening differently in JS where my escape character is being interpreted differently? Thanks!

**Comment by porsager** [comment]
Hi @johndanek 

It is the backslash character which is an escape character in JS strings. That means your query should look like this:

```js
const pages_results = await sql`COPY pages (id, status, type, title) FROM '/tmp/ARCHIVE_PAGES.csv' (FORMAT csv, DELIMITER ';', QUOTE '"', ESCAPE '\\', NULL '\\N');`;
```

It's not optimal since I could have been basing the tagged template handling on [.raw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#raw_strings) which would have felt more correct (no handling of escape sequences). I'm afraid it might be too late to change now (even in a major bump) though as it could lead to real subtle errors for current users.

**Comment by johndanek** [comment]
@porsager That makes sense, thank you for the explanation!
