### ISSUE TITLE
utility query methods

### ISSUE THREAD

**Issue by skarbovskiy** [porsager/postgres#509]
I'm currently migrating from slonik cause of simpler syntax and better performance (great job btw) but have a little suffer of not being able to check returning rows from db in one line like it is done in slonik by `many`, `one`, `maybeOne` methods. 
I tried to monkey patch `sql` to achive something like 
```
await sql.one`SELECT 1`;
```
but it looks ugly. Maybe you have some plans related to this issue?
Thanks

**Comment by skarbovskiy** [comment]
current "monkey patch" way
```
sql.one = async (query, ...params) => {
	let results = await sql(query, ...params);
	if (results.length !== 1) {
		throw new NotFoundError();
	}
	return results[0];
};
```

**Comment by porsager** [comment]
Thanks a lot @skarbovskiy 

I'm a previous pg-promise user which had those helpers as well, and while I also them then, I have not had a need since I could use destructuring with Postgres.js.

Now if you want to keep that way of handling things I would recommend making utility functions to support it, so following your example — this instead:
```
sql.one = async x => {
  const [result] = await x
  if (result.count !== 1)
    throw new NotFoundError()
  return result
}

// usage
const x = await sql.one(sql`
  select 1
`)
```

**Comment by skarbovskiy** [comment]
My variant use less "sql" keywords. Any edge cases it can fail?

**Comment by e3dio** [comment]
Make any function you want, no problem doing that:
```javascript
const sql1 = (...args) => sql(...args).then(r => r[0]);

const result = await sql1`select 1`; 
```
