### ISSUE TITLE
Table/Columns names with " don't seem to play well

### ISSUE THREAD

**Issue by jordan-bonecutter** [porsager/postgres#511]
I have two tables, one named `telem."channel-1.power.real"` and `telem."channel-2.power.real"` and I want to dynamically choose between the two a la:

```js
function select(table1) {
  return sql`SELECT * FROM ${ sql(table1 ? `telem."channel-1.power.real"` : `telem."channel-2.power.real"`) }`
}
```

But I think the interpolation is too smart, I get an error like:
```
PostgresError: improper qualified name (too many dotted names): telem."channel-1.power.real"
```

Any way around this?

**Comment by porsager** [comment]
So is you table name actually `telem."channel-1.power.real"` or is your schema name `telem` and your table name `channel-1.power.real`? Even so, if you have periods in your table name, then yes, that will fail with the current interpolation which handles `schema.table` strings by escaping them separately to `"schema"."table"`.

Now you could get around this by using fragments since you only have 2 options, but I think what you tried to do above is what the docs suggests, so it's worth looking into..

```
function select(table1) {
  return sql`SELECT * FROM ${ table1 ? sql`telem."channel-1.power.real"` : sql`telem."channel-2.power.real"` }`
}
```

**Comment by jordan-bonecutter** [comment]
I see, this does seem to work! My only concern is that this won't protect against injection, right?

**Comment by porsager** [comment]
It will actually protect better because the only two possible values would be `telem."channel-1.power.real"` and `telem."channel-2.power.real"` :) If you notice you are not even passing a dynamic variable anywhere this way. 

Basically you are safe from sql injections unless you use sql.unsafe().
