### ISSUE TITLE
Starting a transaction withing a transaction commit to the database

### ISSUE THREAD

**Issue by vafanassieff** [porsager/postgres#554]
Hey, using `postgres` since v1, you made me appreciate SQL in JS !

I'm having an issue, iIuse SQL transactions to isolate my integrations tests, each one have their own sql tx.
I instantiate the client for the tx this way :

```
import postgres from 'postgres'
const sql = postgres({ max: 1 })
await sql`BEGIN`
```

And then when the test is finished I call

```
sql`ROLLBACK`
```

It's working great unless when we have `sql.begin` somewhere, the call of begin trigger 

`2023-02-13 17:55:03.344 UTC [5865] WARNING:  there is no transaction in progress` in the database log

When the `sql.begin` end there is an automatic call to `COMMIT` even if we are already in a tx, is there a way to avoid this issue ?
A way to define if we should call commit or not ?

Best !

**Comment by porsager** [comment]
Hi @vafanassieff 

Thanks a lot for the kind words!

I've been thinking to add sql.rollback() so that you don't have to explicitly throw and catch the transaction to make it rollback, but I don't know when I'll have more time to ponder that.

The issue is that you can't have nested transactions in PostgreSQL, but you have to use savepoints. That's why I made the transaction api explicit in js. 

I haven't made any effort to support using transactions outside the sql.begin api, even though I can see it makes perfekt sense with postgres({ max: 1 }).
