### ISSUE TITLE
Support for Cloudflare Workers TCP `connect()`?

### ISSUE THREAD

**Issue by karlhorky** [porsager/postgres#598]
Hey @porsager 👋 hope you're well! 

[Cloudflare announced TCP `connect()` from Cloudflare Workers](https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases/) recently, and they mentioned that `pg` has support out of the box:

> `pg`, the most widely used JavaScript database driver for PostgreSQL, works on Cloudflare Workers today, with more database drivers to come.
>
> We’ve worked with the maintainers of `pg`, one of the most popular database drivers in the JavaScript ecosystem, used by ORMs including Sequelize and knex.js, to add support for `connect()`.

Maybe this is done in these commits:

https://github.com/brianc/node-postgres/compare/18b8ceae17f89b70b06d9eb9e5fe0e0f9dedda2e..14b840e96e57fc0617b5c4758f6318f774148ee4

Maybe `postgres` can also support TCP connections from Cloudflare Workers?

**Comment by porsager** [comment]
Wuhuu. Can't see why it shouldn't 😃 Have you tried it as is?

**Comment by porsager** [comment]
Ok got it working now with wrangler locally 🎉

**Comment by karlhorky** [comment]
Amazing, thanks @porsager 🙌

- 👀 PR here: #599

**Comment by superboss224** [comment]
With the version from the cloudflare branch, I'm getting : 
```
01:18:22.523 | ✘ [ERROR] Could not resolve "os"
01:18:22.523 |  
01:18:22.524 | node_modules/postgres/src/index.js:1:15:
01:18:22.524 | 1 │ import os from 'os'
01:18:22.525 | ╵                ~~~~
01:18:22.525 |  
01:18:22.525 | The package "os" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
01:18:22.525 |  
01:18:22.526 | ✘ [ERROR] Could not resolve "fs"
01:18:22.526 |  
01:18:22.527 | node_modules/postgres/src/index.js:2:15:
01:18:22.527 | 2 │ import fs from 'fs'
01:18:22.527 | ╵                ~~~~
01:18:22.527 |  
01:18:22.528 | The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```
Is there something I'm doing wrong ? Or should I just wait until everything is merged ?

**Comment by elithrar** [comment]
@superboss224 you need to set `node_compat = true` in your `wrangler.toml`.

**Comment by superboss224** [comment]
@elithrar Hello, thank you for your fast answer !
 I'm using SvelteKit so maybe it's bugging my build somehow, but I already have `node_compat = true` in my wrangler.toml
 
 I'm using adapter-auto instead of adapter-cloudflare but I don't think that it's the source of the issue, I can still try to change my adapter

**Comment by superboss224** [comment]
Even with cloudflare adapter, I still get the same error

In my package.json :
```
	"dependencies": {
		"postgres": "github:porsager/postgres#cloudflare"
	}
```

Is that the right way of importing it ?

**Comment by superboss224** [comment]
And, is there a way to be sure that node_compat is true in building logs ? Does cloudflare show something specific about it ?

**Comment by superboss224** [comment]
Hello @porsager, I have more news about my issue : 
The flag `node_compat = true` works for a cloudflare **worker**, but it's not available on cloudflare pages, because cloudflare considers it as legacy, so they may not support it in the future

Instad, there is a new flag named `nodejs_compat` that seem to support less polyfilling

More info about the differences between those two flags here : 
https://developers.cloudflare.com/workers/wrangler/configuration/#add-polyfills-using-wrangler

Would it be possible to support the new `nodejs_compat` flag to have the module working in cloudflare pages, and with the newest and recommended configuration for cloudflare ?

**Comment by porsager** [comment]
Let's track this in the PRs ;) I hope we can iron out the rest during this week..

**Comment by karlhorky** [comment]
Here are the two current open PRs to watch:

- #599
- https://github.com/porsager/postgres/pull/618

**Comment by karlhorky** [comment]
Update: @Ethan-Arrowood from Vercel has started a WinterCG specification on `connect()` for TLS connections, maybe it becomes a cross-runtime standard 😮

- https://github.com/porsager/postgres/pull/618#issuecomment-1739562595
