### ISSUE TITLE
Clarification of dynamic identifiers

### ISSUE THREAD

**Issue by timonson** [porsager/postgres#629]
Can you please clarify one topic for me? Here are two different ways of generating a query. 

```ts
const table = 'users'
    , column = 'id'

sql`
  select ${ sql(column) } from ${ sql(table) }
`

sql`
  select ${column} from ${table}
`
```

Why would you recommend the former and not the latter way of generating the query? What exactly is `sql`doing in the former example.

Connected to this question: What is the best way to write the following query with postgres function `gen_salt`?

```ts
async function insertAccount(
  { owner, email, contact, password }: AccountInput,
) {
  return await sql`
    INSERT INTO public.account (owner, email, contact, hashed_password)
    VALUES (${owner}, ${email}, ${contact as any}, crypt(${password}, gen_salt('md5')))
    RETURNING *`;
}
```

Thank you very much!

**Comment by porsager** [comment]
The second option won't work since both the column name and the table name are identifiers and not values, so they can't be passed as parameters and need to be serialized in the query. That is what `sql()` does. It ensures we're serializing the value as an identifier, and marks it as such for the query string generation.

**Comment by timonson** [comment]
Thank you!
