### ISSUE TITLE
Error on SvelteKit

### ISSUE THREAD

**Issue by kenbankspeng** [porsager/postgres#653]
Strange. FYI. Able to use this library in Vanilla / React / NextJS but not with Svelte.

On @sveltejs/kit 1.22.3, this: 
   `import postgres from 'postgres';`

causes this error: 
   `ReferenceError: Buffer is not defined at bytes.js`

**Comment by lj-n** [comment]
Hi, i'm having the same issue on `"@sveltejs/kit": "1.25.0"`.
Did you manage to make it work somehow?

**Comment by Damato** [comment]
Still an issue, even on Sveltekit 4

**Comment by porsager** [comment]
How can you even come to that conclusion when you're only seeing issues together with Sveltekit. 

Seeing that the original creator closed the issue also pretty much points to him realizing he had understood something wrongly after all.

It's disingenuous to just throw accusations around trying to have someone else do your work for you. Had you commented with a bit more humility you might have gotten a more valuable response that could get you further in your debugging.

**Comment by Damato** [comment]
Sorry @porsager, but I have the exact issue on SvelteKit 4, hence I searched as one does and found his issue. Closed. Which he closed inferring he got a workaround. I asked how he resolved this, and did not ask for a 3rd party to call me disingenuous. 

These are facts, as I am running a stock SvelteKit 4 project, and after a strait forward install of Postgress it fails on the second line of `bytes.js` with `ReferenceError: Buffer is not defined`. Meaning it is literally the same issue. This was a genuine question and not to pick a fight. I merely asked him how he fixed it, as it may be an issue I don't know about as he did not give an answer. 

I hope you don't represent the community, as honestly that is a toxic response on a question based on fact in front of me. I did not ask him to fix my homework, nor did I disparage Postgres.

**Comment by Damato** [comment]
@porsager you are right, sorry. I asked a question, you took offense. 
The intent was not to pick a fight, but honestly I am happy to use another library. 

For the next person that comes across this issue: 
The issue was on `bytes.js`, the full error `ReferenceError: Buffer is not defined at bytes.js:2:14`
> let buffer = Buffer.allocUnsafe(size)

**Comment by porsager** [comment]
You could simply have left out the "trust this is a postgres issue" part. 

Thanks for editing your latest reply, it shows good will to continue in a better way. 

So. Buffer is a node class, and if it is undefined it would seem like Sveltekit is importing  Postgres.js in a browser context. I guess you might be trying server side rendering expecting Postgres.js to work for the server side part of your app. This still makes it a Svelte kit issue since it's wrongly importing Postgres.js for the frontend. Perhaps you can more easily find the issue now.
