### ISSUE TITLE
Cannot execute multiple statements with sql.file

### ISSUE THREAD

**Issue by nikku** [porsager/postgres#86]
Likely related to https://github.com/porsager/postgres/issues/76 my intuitive notion of `sql.file` was that I am able to execute arbitrary SQL files. However, at the moment it looks like postgress will attempt to wrap everything in a prepared statement that does not support more than one statement?

Example `create.sql` file:

```sql
CREATE TABLE foo (
  id numeric
);

CREATE TABLE bar (
  id numeric
);
```

Executing this one fails on the postgres side with:

```
PostgresError: cannot insert multiple commands into a prepared statement
```

I'm on v2.0.0-beta.0 but the issue exists on v1.0.0, too.

**Comment by porsager** [comment]
The query will be executed as a simple query if you don't pass a second argument to ```sql.file()```. 

The postgres protocol doesn't allow passing parameters in simple queries so you can't have multiple statements in the same file while also using positional parameters.

I would think that if you get the above error it is because you run it like this:

```js
sql.file('create.sql', [])
```
